import numpy as np

x = np.random.rand(3, 2)
print(x)
x = np.random.rand(5)
print(x)
x = np.random.randint(1, 10)
print(x)
np.random.seed(0)
a = np.random.rand(5)
print(a)
np.random.seed(0)
a = np.random.rand(5)
print(a)
a = np.arange(5)
print(a)
np.random.shuffle(a)
print(a)
arr = np.arange(9).reshape((3, 3))
print(arr)
np.random.shuffle(arr[0])
print(arr)
a = np.array([1, 1, 2, 3, 4, 5, 6, 7, 1, 2, 2, 4, 3, 5, 6])
print(np.unique(a))
